localsite/urls.py
from django.conf.urls.defaults import *

handler404 = 'localsite.views.my404view'
from django.views.generic.simple import direct_to_template

# urlpatterns = patterns('',
#     url(r"^$", 'localsite.views.home', name="home"),
# )

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

#from localsite.urls import urlpatterns

from satchmo_store.urls import urlpatterns

#from autocomplete.views import autocomplete

urlpatterns += patterns('',
    #url(r'^autocomplete/', include(autocomplete.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),    
    url(r'^matiere/([\w-]+)/$', 'localsite.views.matiere_list', {}, name="matiere_list"),
    url(r'^fabricant/([\w-]+)/$', 'localsite.views.fabricant_list', {}, name="fabricant_list"),
)


from satchmo_utils import urlhelper

urlhelper.replace_urlpatterns(
    urlpatterns,
    [
        #add override urls here (match the name from satchmo's url files)
        url(r'^$', 'localsite.views.home', {}, name='satchmo_shop_home'),
    ]
)

localsite/models.py
from product.models import Product
from django.db import models
from satchmo_utils.thumbnail.field import ImageWithThumbnailField
from django.core.urlresolvers import reverse
from singleton_models.models import SingletonModel


class Matiere(models.Model):
    product = models.ManyToManyField(Product, blank=True, null=True)
    name = models.CharField("Nom", max_length=30)
    slug = models.SlugField("Slug", blank=True, unique=True)
    description = models.TextField("Description", blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('matiere_list', args=[self.slug])

    class Meta:
        ordering = ['name']


class Fabricant(models.Model):
    product = models.ManyToManyField(Product, blank=True, null=True)
    name = models.CharField("Nom", max_length=30)
    slug = models.SlugField("Slug", blank=True, unique=True)
    description = models.TextField("Description", blank=True)
    picture = ImageWithThumbnailField('Logo', blank=True, null=True,
        upload_to="logos",
        name_field="name",
        max_length=200)  # Media root is automatically prepended

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('fabricant_list', args=[self.slug])

    class Meta:
        ordering = ['name']


class PubAccueil(SingletonModel):
    logo = models.ImageField(upload_to='pub/')
    link = models.CharField('lien', blank=True, max_length=250, help_text='optionnel')

    # def __unicode__(self):
    #     return

    class Meta:
        verbose_name = "Encart pub accueil"
        verbose_name_plural = "Encart pub accueil"

localsite/views.py
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404,redirect,render_to_response
from product.models import Product
from localsite.models import Matiere,Fabricant

def my404view(request):
    return redirect('/')

from product.models import Category

def home(request):
    rdict ={}
    rdict['int_cats'] = Category.objects.filter(parent__slug='collections-interieur')
    rdict['ext_cats'] = Category.objects.filter(parent__slug='collections-exterieur')
    return render_to_response('shop/index.html',rdict,RequestContext(request))


def matiere_list(request, slug):
    rdict ={}
    matiere = Matiere.objects.get(slug=slug)
    rdict['category'] = {'name':matiere.name, 'description':matiere.description}
    rdict['products'] = Product.objects.filter(matiere__slug=slug)
    return render_to_response('product/category.html', rdict, context_instance=RequestContext(request))

def fabricant_list(request, slug):
    rdict ={}
    fabricant = Fabricant.objects.get(slug=slug)
    rdict['category'] = {'name':fabricant.name, 'description':fabricant.description}
    rdict['logo'] = fabricant.picture
    rdict['products'] = Product.objects.filter(fabricant__slug=slug)
    return render_to_response('product/category.html', rdict, context_instance=RequestContext(request))

templates/base.html
{% load i18n satchmo_category satchmo_google satchmo_util app_plugins normalize_decimal %}{% block doctype %}<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% endblock %}
<head>
    {% block extra-head %}{% endblock %}
    {% block stylesheet %}
        <link rel="stylesheet" href="{{ media_url }}css/reset.css" type="text/css" />
        <link rel="stylesheet" href="{{ media_url }}css/960.css" type="text/css" />
        <link rel="stylesheet" href="{{ media_url }}css/font.css" type="text/css" />
        <link rel="stylesheet" href="{{ media_url }}css/style.css" type="text/css" />
        <link rel="stylesheet" href="{{ media_url }}css/diaporama.css" type="text/css" />
    {% endblock %}
    <title>{% block title %}Base{% endblock %} - {{ shop_name }}</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
    
    {% plugin_point "page_head" %}
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"></script>
    {% block javascript %}
    {% endblock %}
</head>
<body>
<div id="ombre" class="container_12">
    
<div id="entete" class="container_12">
    
    <h1>Meubles de jardin</h1>
    <span id="mobilier" class="slogan">mobilier</span>
    <span id="int-ext" class="slogan">extérieur intérieur</span>
    <a href="/"><img alt="logo" id="logo" src="{{ media_url }}images/logo.png" border="0" /></a>

    <div id="contact">
        Renseignements<br/>
        <b> 04 73 61 65 45</b><br/>
        <a href="/contact/">contactez-nous</a>
    </div>

    <div id="menubar">

    <a href="/" id="lien_collections">
        <img src="{{ media_url }}images/icone-maison.png" alt="Collections" /> Collections
    </a>

    <ul id="navigation">
        <li><a href="/categorie/articles/parasols/"><img src="{{ media_url }}images/icone1.png" alt="Parasols" /> Parasols</a></li>
        <li><a href="/categorie/articles/bains-de-soleil/"><img src="{{ media_url }}images/icone2.png" alt="Bains de soleil" /> Bains de soleil</a></li>
        <li><a href="/categorie/articles/fauteuils/"><img src="{{ media_url }}images/icone3.png" alt="Fauteuils" /> Fauteuils</a></li>
        <li><a href="/categorie/articles/chaises/"><img src="{{ media_url }}images/icone4.png" alt="Chaises" /> Chaises</a></li>
        <li><a href="/categorie/articles/tables/"><img src="{{ media_url }}images/icone5.png" alt="Tables" /> Tables</a></li>
        <li><a href="/categorie/articles/canapes/"><img src="{{ media_url }}images/icone6.png" alt="Canapés" /> Canapés</a></li>
        <li><a href="/categorie/articles/chambres/"><img src="{{ media_url }}images/icone7.png" alt="Chambres" /> Chambres</a></li>
        <li><a href="/categorie/articles/rangements/"><img src="{{ media_url }}images/icone8.png" alt="Rangements" /> Rangements</a></li>
    </ul>


    </div>

</div>




 <div class="container_12">
    <div id="page">
        
        
        {% block content %}
        <div class="grid_9 blanc">
            {% block navbar %}
            {% endblock %}
            <!--contenu-->
    
        </div>
        {% endblock %}
        


{% block colonne %}
{% endblock %}


    </div>



    <div class="clear"></div>

    <div id="footer">
        {% block footer %}
        

        
        <div class="grid_4">
            
            <div id="coord">
            <!--<img src="{{ media_url }}images/logo_gris.jpg" alt="Tendance Garden"/>-->
            
            <img src="{{media_url}}images/magasin.jpg" width="190"/>
            <br/><br/>
            
            <address>
                   <a href="http://maps.google.fr/maps?q=rue+de+milan+lempdes&hl=fr&ll=45.776099,3.205004&spn=0.008561,0.021136&sll=46.75984,1.738281&sspn=8.611865,21.643066&vpsrc=6&t=h&z=16">    
                   <img id="carte" src="{{media_url}}images/carte.png">
                   </a>   
                <strong>Tendance Garden</strong><br/>
                Rue de Milan<br/>
                63370 Lempdes<br/><br/>
                <b class="tel">Tel : 04 73 61 65 45</b><br/>
                <a id="email" href="/contact/">contactez-nous par email</a>
                
            </address>
            </div>
        </div>
        
        <div class="footlinks grid_2">
            {% regroup categories by parent as cat_list %}
            
            <h3>INTERIEUR / INDOOR</h3>
            <ul>
            {% for c in categories %}
            {%  if c.parent.slug == 'collections-interieur' %}                
                <li><a href="{{c.get_absolute_url}}">{{c.name}}</a>
                {% if c.get_all_children %}
                    <ul class="bulls">
                        {% for sc in c.get_all_children %}
                        <li><a href="{{sc.get_absolute_url}}">{{sc.name}}</a></li>
                        {% endfor %}
                        </ul>
                {% endif %}
                </li>
            {% endif %}
            {% endfor %}
            </ul>
        </div>


        <div class="footlinks grid_2">
            <h3>EXTERIEUR / OUTDOOR</h3>
            <ul>
            {% for c in categories %}
            {%  if c.parent.slug == 'collections-exterieur' %}                
                <li><a href="{{c.get_absolute_url}}">{{c.name}}</a>
                {% if c.get_all_children %}
                    <ul class="bulls">
                        {% for sc in c.get_all_children %}
                        <li><a href="{{sc.get_absolute_url}}">{{sc.name}}</a></li>
                        {% endfor %}
                        </ul>
                {% endif %}
                </li>
            {% endif %}
            {% endfor %}
            </ul>
        </div>

        <div class="footlinks grid_2">
            <h3>TOUS LES MEUBLES</h3>
            <ul class="bulls">
            {% for c in categories %}
            {%  if c.parent.slug == 'articles' %}                
                <li><a href="{{c.get_absolute_url}}">{{c.name}}</a>
                {% if c.get_all_children %}
                    <ul class="bulls">
                        {% for sc in c.get_all_children %}
                        <li><a href="{{sc.get_absolute_url}}">{{sc.name}}</a></li>
                        {% endfor %}
                        </ul>
                {% endif %}
                </li>
            {% endif %}
            {% endfor %}
            </ul>
        </div>

        <div class="footlinks grid_2">
            <h3>FABRICANTS</h3>
            <ul class="bulls">
            {% for f in fabricants %}
                <li><a href="{{f.get_absolute_url}}">{{f.name}}</a></li>
            {% endfor %}
            </ul>

            <h3>MATIERES</h3>
            <ul class="bulls">
            {% for m in matieres %}
                <li><a href="{{m.get_absolute_url}}">{{m.name}}</a></li>
            {% endfor %}
            </ul>
        </div>
    
    {% endblock %}
    <p id="w3c">
        <a href="http://validator.w3.org/check?uri=referer"><img
          src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a>
      </p>
    </div>

</div>
</div>

{% block page-close %}
{% block google-tracker %}
{% if shop.options.GOOGLE.ANALYTICS.value %}
    {% show_tracker is_secure %}
{% endif %}
{% endblock %}
{% endblock %}

</body></html>

templates/product/category.html
{% extends "shop/base.html" %}
{% load i18n contains %}
{% load thumbnail %}
{% load satchmo_category %}

{% block title %}{{ category.name }}{% endblock %}


{% block extra-head %}
{% if category.meta %}
    <meta name="description" content="{{ category.meta|escape }}">
{% endif %}


{% endblock %}
{% block javascript %}
    <script type="text/javascript" src="{{media_url}}js/jquery.biggerlink.min.js"></script>
    <script type="text/javascript">
        $(function(){
            $("div.sous-cat").biggerlink();
            $("div.product_listing").biggerlink();
        })
    </script>
{% endblock %}


{% block content %}
<div class="grid_12 blanc product_category_header">


    {% block navbar %}
    <ul id="navbar">
        <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
        {% for parent in category.parents %}<li><a href="{{ parent.get_absolute_url }}">{{ parent.name }}</a></li>{% endfor %}
        <li>{{ category.name }}</li>
    </ul>   
    {% endblock %}


    {% if category.main_image %}
        <img align="left" src="{{media_url}}/{{ category.main_image.picture }}" 
            width="{{ category.main_image.picture.width }}" 
            height="{{ category.main_image.picture.height }}" 
            style="padding-right:20px"
            alt="{{ category.name }}"/>
    {% endif %}
    

    <h3>{{ category.name }}</h3>
    {% if category.description %}
        <p class="product_category_description">{{ category.description|safe}}</p>
    {% endif %}

</div>

<div id="product_category">

{% if category.slug|contains:'collections-' %}

    {% for cat in child_categories %}
        {% if cat.parent.slug|contains:'collections-' %}
            <div class="grid_3 sous-cat">
                <h4>{{cat.translated_name}}</h4>
                {% thumbnail cat.main_image.picture 200 as image %}
                <a href="{{ cat.get_absolute_url }}">
                    <img src="{{media_url}}/{{ cat.main_image.picture }}" 
                        width="{{ cat.main_image.picture.width }}" 
                        height="{{ cat.main_image.picture.height }}" 
                        alt="{{cat.name}}" /></a>
            </div> 
        {% endif %}   
    {% endfor %}
    

{% else %}

    {% if child_categories %}
            {% for cat in child_categories %}
            <div class="grid_3 sous-cat">
                <h4>{{cat.translated_name}}</h4>
                <a href="{{ cat.get_absolute_url }}">
                    <img src="{{media_url}}/{{ cat.main_image.picture }}" 
                        width="{{ cat.main_image.picture.width }}" 
                        height="{{ cat.main_image.picture.height }}" 
                        alt="{{cat.name}}" /></a>
            </div>    
            {% endfor %}
    {% endif %}

{% endif %}


    
    {% for product in products %} 
        {% if forloop.first %} <ul>  {% endif %}
            <li class="grid_4"><div class="product_listing">
                
                <div class="product_wrapper">
                
                {% thumbnail product.main_image.picture 85x85 as image %}
                <a href="{{ product.get_absolute_url }}">
                <img src="{{ image }}" alt="{{ product.translated_name }}" /></a>
                <span class="minidesc">
                
                    <a href="{{ product.get_absolute_url }}">{{ product.translated_name }}</a>
                    <br/>
                    {% if product.category %}<span class="listed_in">
                        {% for cat in product.category.all %}
                        {{ cat.name }}{% if not forloop.last %} - {% endif %}
                        {% endfor %}
                        </span><br/>
                    {% endif %}
                    {% for attr in product.productattribute_set.all %}
                    {% if attr.name == 'matiere' or attr.name == 'dimensions' %}
                    {{ attr.value }}<br/>
                    {% endif %}
                    {% endfor %}
            </span>
            </div>
            </div></li>
        {% if forloop.last %} </ul> {% endif %}
    {% endfor %}
    
    
</div>
<br/><br/>


{% endblock %}

templates/product/product.html
{% extends "shop/base.html" %}
{% comment %}
-------------------------------------------------------------------
This is the base product detail page.
To modify the templates of specific types of products, such as
ProductVariations or CustomProducts, look for product/detail_xxx.html
-------------------------------------------------------------------
{% endcomment %}
{% load i18n %}
{% load thumbnail %}
{% load satchmo_price %}
{% load satchmo_currency satchmo_category %}
{% load satchmo_util satchmo_discounts %}
{% load app_plugins %}

{% block extra-head %}
{% if product.meta %}
    <meta name="description" content="{{product.meta}}">
{% endif %}
{% endblock %}

{% block title %}{{ product.translated_name  }}{% endblock %}

{% block content %}
<div class="grid_12 blanc">


{% block navbar %}
    <ul id="navbar">
    <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
    {% for name, url in product.category.all.0.get_url_name %}
        <li><a href="{{ url }}">{{ name }}</a></li>
    {% endfor %}
    <li>{{ product.translated_name }}</li>
    </ul>
{% endblock %}
<h3>{{ product.translated_name }}</h3>

</div>

<div class="grid_5 blanc">    
    {% for pic in product.productimage_set.all %}
        {% thumbnail pic.picture 380x380 as image %}
        <img src="{{ image }}" width="{{ image.width }}" height="{{ image.height }}" />
    {% endfor %}
    
</div>

<div class="grid_7 blanc">
    <p>{{ product.description|safe }}</p>

<br/>
    <table class="attributes" cellspacing="0" cellpadding="0" border="1">
    {% with product.translated_attributes as atts %}
        {% if atts %}
            {% for att in product.translated_attributes %}
            <tr><th>{{ att.description }}</th><td>{{ att.value }}</td></tr>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% if product.matiere_set.all %}
        {% for m in product.matiere_set.all %}
        <tr><th>Matière</th><td>{{ m.name }}</td></tr>
        {% endfor %}
    {% endif %}
    {% if product.fabricant_set.all %}
        {% for m in product.fabricant_set.all %}
        <tr><th>Fabricant</th><td>{{ m.name }}</td></tr>
        {% endfor %}
    {% endif %}
    
    </table>
</div>

<div class="grid_12 blanc">
<br/>

{% if product.related_items %}


{% for related in product.related_items.all %} 
    {% if forloop.first %} <ul>  {% endif %}
        <li class="grid_4"><div class="product_listing">
            
            <div class="product_wrapper">
            
            {% thumbnail related.main_image.picture 85x85 as image %}
            <a href="{{ related.get_absolute_url }}">
            <img src="{{ image }}" alt="{{ related.translated_name }}" /></a>
            <span class="minidesc">
            
                <a href="{{ related.get_absolute_url }}">{{ related.translated_name }}</a>
                <br/>
                {% if related.category %}<span class="listed_in">
                    {% for cat in related.category.all %}
                    {{ cat.name }}{% if not forloop.last %} - {% endif %}
                    {% endfor %}
                    </span><br/>
                {% endif %}
                {% for attr in related.productattribute_set.all %}
                {% if attr.name == 'matiere' or attr.name == 'dimensions' %}
                {{ attr.value }}<br/>
                {% endif %}
                {% endfor %}
        </span>
        </div>
        </div></li>
    {% if forloop.last %} </ul> {% endif %}
{% endfor %}





{% endif %}
<br/>
</div>
{% endblock %}

templates/shop/contact_form.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Contact Us" %}</li>
{% endblock %}

{% block content %}
<div class="grid_12 blanc">

<h3>Contactez-nous</h3>

{% if form.errors %}
<h3>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h3>
{% endif %}
<form id="contact_form" method="post" action=".">{% csrf_token %}

<table>
    {{ form.as_table }}
<tr><td></td><td><input type="submit" value="{% trans "Send Email" %}"/></td></tr>

</table>
</form>
</div>
{% endblock %}

templates/shop/contact_thanks.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Contact Us" %}</li>
{% endblock %}

{% block content %}
<div class="grid_12 blanc">


<h3>Merci ! </h3>

<p>Nous avons bien receptionné votre demande et vous recontactons le plus rapidement possible</p>

</div>
{% endblock %}

templates/shop/index.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load satchmo_util %}

{% block title %}Accueil{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(function(){
    $("#diaporama").tabs({  fx:{opacity: "toggle"},
                            event: "mouseover"}).tabs("rotate", 5000, true);

    $("#diaporama").hover(
        function() {
            $("#diaporama").tabs("rotate",0,true);
            },
        function() {
            $("#diaporama").tabs("rotate",5000,true);
            }
    );
    $("#collections > li a").click(function(){
        window.location = $(this).attr('rel');
    });

    /*$("#collections > li").hover(
        function() {
            $(this).addClass('ui-state-hover');
            $(this).addClass('ui-tabs-selected');
        }
        ,function() {
            //$(this).removeClass('ui-state-active');
            $(this).removeClass('ui-state-hover');
            $(this).removeClass('ui-tabs-selected');
        }
        );*/
});


</script>
{% endblock %}


{% block content %}
<div class="grid_9 blanc">

<div id="diaporama" >
    <ul class="ui-tabs-nav gamme" id="collections">

        {% for cat in int_cats %}
        <li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-{{ cat.id }}">
        <a href="#fragment-{{ cat.id }}" rel="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
        {% endfor %}

        <br/><br/>

        {% for cat in ext_cats %}
        <li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-{{ cat.id }}">
        <a href="#fragment-{{ cat.id }}" rel="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
        {% endfor %}

    </ul>

    <div id="cadrediapo">
        {% for cat in int_cats %}
        <div id="fragment-{{cat.id}}" class="ui-tabs-panel" style="">
            <img src="{{media_url}}/{{ cat.main_image.picture }}" alt="" />
            <div class="info" >
            <h2><a href="{{ cat.get_absolute_url }}" >Découvrez la gamme {{cat.name}}</a></h2>
            <p><a href="{{ cat.get_absolute_url }}" >{{cat.description|safe}}</a></p>
            </div>
        </div>
        {% endfor %}
        {% for cat in ext_cats %}
        <div id="fragment-{{cat.id}}" class="ui-tabs-panel" style="">
            <img src="{{media_url}}/{{ cat.main_image.picture }}" alt="" />
            <div class="info" >
            <h2><a href="{{ cat.get_absolute_url }}" >Découvrez la gamme {{cat.name}}</a></h2>
            <p><a href="{{ cat.get_absolute_url }}" >{{cat.description|safe }}</a></p>
            </div>
        </div>
        {% endfor %}


    </div>
</div>
</div>

{% endblock %}

{% block colonne %}

<div class="grid_3 blanc">

    <div id="colonne">

        <div id="pub"><img src="/static/pub/pubWeb_TG_foire2012_anim.gif" border="0"></div>


    </div>

</div>

{% endblock %}